# Generated by Django 5.2.14 on 2026-06-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='actual_price_per_unit',
        ),
    ]
