# Generated by Django 5.2.14 on 2026-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cart_user_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('manage_orders', 'Can manage orders'), ('change_status', 'Can change order status')]},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordinato'), ('DELIVERED', 'Consegnato'), ('PROCESSING', 'In Elaborazione')], default='ORDERED', max_length=20),
        ),
    ]
