# Generated by Django 5.2.14 on 2026-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_used',
            field=models.EmailField(default='temp@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='xyz', max_length=255),
            preserve_default=False,
        ),
    ]
