# Generated by Django 5.2.14 on 2026-07-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email_used_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
