# Generated by Django 5.2.14 on 2026-07-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('manage_orders', 'Can manage orders')]},
        ),
    ]
