# Generated by Django 5.2.14 on 2026-07-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': (['-created_at'],), 'permissions': [('manage_orders', 'Can manage orders')]},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='actual_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
