# Generated by Django 5.2.14 on 2026-07-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('manage_orders', 'Can manage orders')]},
        ),
    ]
