# Generated by Django 5.2.14 on 2026-07-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user__username', '-created_at'], 'permissions': [('manage_orders', 'Can manage orders')]},
        ),
    ]
